/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.al;

import org.junit.Test;
import static org.junit.Assert.*;

public class al01 {
    @Test public void appHasAGreeting() {
        //al01 classUnderTest = new al01();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}